account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    # path('login/', views.login_user, name='login'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', views.dashboard, name='dashboard'),
    # Change password urls
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    # Reset password urls
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # User Registration
    path('register/', views.register, name='register'),
    # Edit user
    path('edit/', views.edit, name='edit'),
]

bookmarks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace='images')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path
from . import views

app_name = 'images'

urlpatterns = [
    path('create/', views.image_create, name='create'),
    path('detail/<int:id>/<slug:slug>/', views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
    path('', views.image_list, name='list'),
]

account/models.py
from django.db import models
from django.conf import settings


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d', blank=True)

    def __str__(self):
        return f'Photo for user {self.user.username}'

account/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput, label='Password')
    password2 = forms.CharField(widget=forms.PasswordInput, label='Confirm Password')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords do not match')
        return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')
        

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('date_of_birth', 'photo')

account/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import LoginForm, UserRegistrationForm, UserEditForm, ProfileEditForm
from .models import Profile


def login_user(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(
                request, username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('Authenticated User')
                else:
                    return HttpResponse('Disabled user account')
            else:
                return HttpResponse('User does not exist')
    else:
        form = LoginForm()
    return render(request, 'account/login.html', {'form': form})


@login_required
def dashboard(request):
    return render(request, 'account/dashboard.html', {'section': 'dashboard'})


def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            # Create a new user object but don't save it yey
            new_user = form.save(commit=False)
            # Set the new password
            new_user.set_password(form.cleaned_data['password'])
            # Save the new user
            new_user.save()
            Profile.objects.create(user=new_user)
            return render(request, 'account/register_done.html', {'new_user': new_user})
    else:
        form = UserRegistrationForm()
    return render(request, 'account/register.html', {'form': form})


@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile, data=request.POST,
                                       files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Profile updated successfully')
        else:
            messages.error(request, 'Error updating your profile')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(
            instance=request.user.profile, files=request.FILES)
    return render(request, 'account/edit.html', {'user_form': user_form,
                                                 'profile_form': profile_form})

account/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <script type="text/javascript"> (function() { var css = document.createElement('link'); css.href = 'https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'; css.rel = 'stylesheet'; css.type = 'text/css'; document.getElementsByTagName('head')[0].appendChild(css); })(); </script>
    <link href="{% static 'css/base.css' %}" rel="stylesheet"/>
    <link rel="stylesheet" href="{% static "css/app.css" %}">
    <link rel="stylesheet" href="{% static "css/theme.css" %}">

</head>

<body>

    {% include "navigation.html" %}
    <main role="main">
    <section class="mt-4 mb-5">

    <div class="container mb-4">
     {% block h1 %}{% endblock %}
    {% if request.user.is_authenticated %}
        {% include "category.html" %}
    {% endif %}
    </div>
    {% block content %}
    {% endblock %}



    </section>

    </main>

    <script src="{% static "js/app.js" %}"></script>
    <script src="{% static "js/theme.js" %}"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/js-cookie@2.2.1/src/js.cookie.min.js"></script>
      <script>
        var csrftoken = Cookies.get('csrftoken');
        function csrfSafeMethod(method) {
          // these HTTP methods do not require CSRF protection
          return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $.ajaxSetup({
          beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
              xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
          }
        });

        $(document).ready(function(){
          {% block domready %}
          {% endblock %}
        });
      </script>

</body>

</html>

account/templates/category.html
<div class="row">
    <nav class="navbar navbar-expand-lg navbar-light bg-white pl-2 pr-2">
    <button class="navbar-light navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExplore" aria-controls="navbarsDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarsExplore">
        <ul class="navbar-nav">
            <li class="nav-item">
            <a class="nav-link" href="#">Lifestyle</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="#">Food</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="#">Home</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="#">Travel</a>
            </li>
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">More</a>
            <div class="dropdown-menu shadow-lg" aria-labelledby="dropdown01">
                <a class="dropdown-item" href="#">Astronomy</a>
                <a class="dropdown-item" href="#">Nature</a>
                <a class="dropdown-item" href="#">Cooking</a>
                <a class="dropdown-item" href="#">Fashion</a>
                <a class="dropdown-item" href="#">Wellness</a>
                <a class="dropdown-item" href="#">Dieting</a>
            </div>
            </li>
        </ul>
    </div>
    </nav>
</div>

account/templates/navigation.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
    <a class="navbar-brand font-weight-bolder mr-3" href="{% url "dashboard" %}"><img src="{% static "img/logo.png" %}"></a>
    <button class="navbar-light navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsDefault" aria-controls="navbarsDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsDefault">
    {% if request.user.is_authenticated %}
    	<ul class="navbar-nav mr-auto align-items-center">
    		<form class="bd-search hidden-sm-down">
    			<input type="text" class="form-control bg-graylight border-0 font-weight-bold" id="search-input" placeholder="Search..." autocomplete="off">
    			<div class="dropdown-menu bd-search-results" id="search-results">
    			</div>
    		</form>
    	</ul>
    {% endif %}
    	<ul class="navbar-nav ml-auto align-items-center">
        {% if request.user.is_authenticated %}
    		<li class="nav-item">
    		<a {% if section == "dashboard" %}class="nav-link active" {% else %}class="nav-link"  {% endif %}href="{% url 'dashboard' %}">My Dashboard</a>
    		</li>
            <li class="nav-item">
    		<a {% if section == "images" %}class="nav-link active" {% else %}class="nav-link" {% endif %}href="{% url 'images:list' %}">Images</a>
    		</li>
            <li class="nav-item">
    		<a {% if section == "people" %}class="nav-link active" {% else %}class="nav-link" {% endif %}href="#">People</a>
    		</li>
    		<li class="nav-item">
    		<a class="nav-link" href="#"><img class="rounded-circle mr-2" src="{% static "img/av.png" %}" width="30"><span class="align-middle">{{ request.user.first_name }}</span></a>
    		</li>
        {% endif %}
        {% if request.user.is_authenticated %}
    		<li class="nav-item">
                <a href="{% url "logout" %}" class="nav-link">Logout</a>
            {% else %}
                <a href="{% url "login" %}">Login</a>
        {% endif %}

    		</li>
    	</ul>

    </div>


    </nav>